package com.stepanok.bulava.demo

/**
 * Everything the demo Mac says, in the three languages the app speaks. On a real Mac these words
 * come from Bulava itself, in the Mac's language; here they follow the phone's.
 */
internal data class DemoText(
    val language: String,
    val macName: String,
    val you: String,
    val bulava: String,
    // Statuses
    val statusWorking: String,
    val statusReplied: String,
    val statusNeedsAnswer: String,
    val statusNeedsOk: String,
    val statusRunning: String,
    val statusReportReady: String,
    val statusMerged: String,
    val statusNext: String,
    val writing: String,
    val stop: String,
    val stopped: String,
    val edit: String,
    val notDelivered: String,
    val notInDemo: String,
    val alreadyHandled: String,
    val untitled: String,
    // Composer and readiness
    val automatic: String,
    val automaticAt: String,
    val newestOfEach: String,
    val fixedVersion: String,
    val claudeThinks: String,
    val codexThinks: String,
    val low: String,
    val medium: String,
    val high: String,
    val veryHigh: String,
    val maximum: String,
    val readyEngine: String,
    val readyClaude: String,
    val readyCodex: String,
    // Buttons
    val yesDoIt: String,
    val notNow: String,
    val leftAsIs: String,
    val openReport: String,
    val askForChanges: String,
    val mergeIt: String,
    val mergeConfirm: String,
    val merged: String,
    val workingOnIt: String,
    val reviewedReady: String,
    val trustTitle: String,
    val trustAndSend: String,
    // Products
    val ledgerName: String,
    val ledgerBrief: String,
    val ledgerSummary: String,
    val ledgerRules: String,
    val cafeName: String,
    val cafeBrief: String,
    val cafeSummary: String,
    val cafeRules: String,
    // Chat: sync
    val syncTitle: String,
    val syncAsk: String,
    val syncSteps: List<String>,
    val syncAnswer: String,
    val syncWorkSteps: List<String>,
    val syncTask: String,
    // Chat: TestFlight
    val shipTitle: String,
    val shipAsk: String,
    val shipSteps: List<String>,
    val shipLead: String,
    val shipEyebrow: String,
    val shipHeadline: String,
    val shipSituation: String,
    val shipItem: String,
    val shipOption42: String,
    val shipOption42Detail: String,
    val shipOptionBump: String,
    val shipOptionBumpDetail: String,
    val shipRecommendation: String,
    val shipUnblocks: String,
    val shipAfterSteps: List<String>,
    val shipDone: String,
    val shipEvent: String,
    // Chat: dark charts
    val chartsTitle: String,
    val chartsAsk: String,
    val chartsSteps: List<String>,
    val chartsAnswer: String,
    val chartsWorkSteps: List<String>,
    val chartsTask: String,
    // Chat: landing page
    val landingTitle: String,
    val landingAsk: String,
    val landingSteps: List<String>,
    val landingAnswer: String,
    val landingTask: String,
    // Anything the person writes
    val genericSteps: List<String>,
    val genericWorkSteps: List<String>,
    val genericAnswer: (product: String, request: String) -> String,
    val genericTask: (request: String) -> String,
    // Context
    val kindFolder: String,
    val kindWebsite: String,
    val canEdit: String,
    val askBeforeEditing: String,
    val modified: String,
    val added: String,
    val checkLastExpense: String,
    val checkOldTests: String,
    val checkPassedCount: String,
    val nextWidgets: String,
    val variantsTitle: String,
    val variantA: String,
    val variantB: String,
    val everythingSoFar: String,
    val latestReport: String,
    val oneReport: String,
    val createReport: String,
    val reportNote: String,
    // Limits, in the words of the Mac's sidebar
    val limits: String,
    val limitSession: String,
    val limitWeekly: String,
    /** "%d" is the share used. */
    val limitUsed: String,
    val limitResetsSession: String,
    val limitResetsCodex: String,
    val limitResetsWeekly: String,
    /** The pace beside a meter, in the words of the Mac's sidebar. */
    val paceAhead: String,
    val paceRoom: String,
    val paceEven: String,
    // Skills
    val skillReview: String,
    val skillNotes: String,
    val serverGitHub: String,
    val serverXcode: String,
    val twoDaysAgo: String,
    val lastWeek: String,
    val today: String,
    val cmdReview: String,
    val cmdTest: String,
    val cmdNotes: String,
    // Reports
    val reportEyebrow: String,
    val reportChanged: String,
    val reportChecked: String,
    val reportBefore: String,
    val reportAfter: String,
    val reportInside: String,
    val reportDemoNote: String,
    val syncReportSummary: String,
    val chartsReportSummary: String,
    val landingReportSummary: String,
    val landingBeforeCopy: String,
    val landingAfterCopy: String,
    val variantReportSummary: String,
    val genericReportSummary: String,
    val productReportSummary: String,
    // Questions for you: a report that asks to decide
    val planTitle: String,
    val planAsk: String,
    val planAnswer: String,
    val planQuestionsTitle: String,
    val planLede: String,
    val questionsForYou: String,
    val openQuestions: String,
    /** "%s" is the questions' title. */
    val waitsForDecisions: String,
    val optTake: String,
    val optLater: String,
    val optNo: String,
    val planWidgets: String,
    val planWidgetsDetail: String,
    val planWidgetsDoc: String,
    val planExport: String,
    val planExportDetail: String,
    val planExportDoc: String,
    val planFamily: String,
    val planFamilyDetail: String,
    val planFamilyDoc: String,
    val planDemoNote: String,
)

internal fun demoText(language: String): DemoText = when (language.lowercase().take(2)) {
    "uk" -> UK
    "ru" -> RU
    else -> EN
}

private val EN = DemoText(
    language = "en",
    macName = "Demo Mac",
    you = "You",
    bulava = "Bulava",
    statusWorking = "Bulava is working",
    statusReplied = "Bulava replied",
    statusNeedsAnswer = "Needs your answer",
    statusNeedsOk = "Needs your OK",
    statusRunning = "Running",
    statusReportReady = "Report ready",
    statusMerged = "Merged",
    statusNext = "Next up",
    writing = "Writing the answer",
    stop = "Stop",
    stopped = "Stopped. Nothing more was done.",
    edit = "Edit",
    notDelivered = "Not delivered",
    notInDemo = "That is not part of the demo. With Bulava on your Mac it does what the button says.",
    alreadyHandled = "This was already handled.",
    untitled = "New chat",
    automatic = "Automatic",
    automaticAt = "Automatic · %s",
    newestOfEach = "Newest of each",
    fixedVersion = "A fixed version",
    claudeThinks = "Claude thinks",
    codexThinks = "Codex thinks",
    low = "Low",
    medium = "Medium",
    high = "High",
    veryHigh = "Very high",
    maximum = "Maximum",
    readyEngine = "The work engine is installed",
    readyClaude = "Claude Code is signed in",
    readyCodex = "Codex is signed in",
    yesDoIt = "Yes, do it",
    notNow = "Not now",
    leftAsIs = "Left as it is.",
    openReport = "Open the report",
    askForChanges = "Ask for changes",
    mergeIt = "Merge it in",
    mergeConfirm = "The change goes into main.",
    merged = "Merged into main. It ships with the next build.",
    workingOnIt = "Working on it",
    reviewedReady = "Reviewed by Codex · ready for you",
    trustTitle = "Claude Code asks before working in a folder for the first time.",
    trustAndSend = "Trust and send",
    ledgerName = "Pocket Ledger",
    ledgerBrief = "Expense tracker for iPhone",
    ledgerSummary = "SwiftUI app with iCloud sync and home screen widgets.",
    ledgerRules = "Keep it native. No third-party analytics. Every change comes with a test.",
    cafeName = "Harbor Coffee",
    cafeBrief = "Website for a coffee shop",
    cafeSummary = "Static site: menu, opening hours, how to find the place.",
    cafeRules = "Short sentences. The menu page must load fast on a phone.",
    syncTitle = "Why does sync skip the last expense?",
    syncAsk = "Why does sync skip the last expense of the day?",
    syncSteps = listOf("Reading SyncEngine.swift", "Searching for lastSyncedAt"),
    syncAnswer = "The sync asks iCloud for everything **after** `lastSyncedAt`, and `lastSyncedAt` is set to the time of the last expense itself. So that expense is never newer than the mark, and it waits until the next one pushes the mark forward.\n\n" +
        "```swift\nlet changes = try await store.changes(since: lastSyncedAt)   // strictly after\nlastSyncedAt = changes.last?.date ?? lastSyncedAt\n```\n\n" +
        "The fix is to remember the sync token iCloud returns instead of a date, and to add a test for an expense entered a second before the sync.\n\nWant me to fix it and add the test?",
    syncWorkSteps = listOf("Changing SyncEngine.swift", "Adding a test for the last expense", "Running the tests", "Codex is reviewing the change"),
    syncTask = "Sync keeps the last expense",
    shipTitle = "Ship 2.4 to TestFlight",
    shipAsk = "Ship version 2.4 to TestFlight",
    shipSteps = listOf("Checking App Store Connect"),
    shipLead = "Everything is ready to upload. One thing needs you first.",
    shipEyebrow = "Needs your answer",
    shipHeadline = "Which build number should this upload use?",
    shipSituation = "TestFlight already has build 41 for version 2.4. Uploading 41 again will be rejected.",
    shipItem = "Build number",
    shipOption42 = "42",
    shipOption42Detail = "The next number, nothing else changes",
    shipOptionBump = "Keep 41 and bump the version",
    shipOptionBumpDetail = "The app becomes 2.4.1 (41)",
    shipRecommendation = "42 — the smallest change that goes through.",
    shipUnblocks = "The upload",
    shipAfterSteps = listOf("Archiving the build", "Uploading to App Store Connect"),
    shipDone = "Uploaded. TestFlight shows it to testers once Apple finishes processing, usually within half an hour.",
    shipEvent = "The build is on TestFlight.",
    chartsTitle = "Add dark mode to the charts",
    chartsAsk = "Add dark mode to the charts",
    chartsSteps = listOf("Reading ChartsView.swift", "Reading Assets.xcassets"),
    chartsAnswer = "The charts draw with fixed colours, so in dark mode the grid lines disappear and the labels are black on almost black. " +
        "Switching them to the asset catalogue's semantic colours fixes both, and the widgets pick it up for free.\n\nWant me to do it?",
    chartsWorkSteps = listOf("Moving the chart colours into the asset catalogue", "Checking contrast in light and dark", "Codex is reviewing the change"),
    chartsTask = "Charts follow dark mode",
    landingTitle = "Tighten the landing page copy",
    landingAsk = "The landing page reads too long. Tighten it.",
    landingSteps = listOf("Reading index.html", "Counting words per section"),
    landingAnswer = "Done. The first screen went from 94 words to 31: what the place is, when it is open, and where. The rest moved below the menu. Codex checked that nothing a visitor looks for got lost.",
    landingTask = "Landing page, shorter",
    genericSteps = listOf("Reading the project", "Looking for where this lives"),
    genericWorkSteps = listOf("Making the change", "Running the tests", "Codex is reviewing the change"),
    genericAnswer = { product, request ->
        "**This is the demo**, so this answer was written in advance. With Bulava on your Mac, Claude Code would now be working in the *$product* folder on “$request”, and you would see its answer grow here as it is written.\n\n" +
            "From here it could:\n1. Answer the question with the code in front of it.\n2. Propose a change for you to approve.\n3. Do it, have Codex review it, and bring back a report.\n\nWant to see the third one?"
    },
    genericTask = { request -> "Done: " + request.take(40) },
    kindFolder = "Folder",
    kindWebsite = "Website",
    canEdit = "Can edit",
    askBeforeEditing = "Ask before editing",
    modified = "Modified",
    added = "Added",
    checkLastExpense = "An expense entered a second before the sync is synced",
    checkOldTests = "The existing tests still pass",
    checkPassedCount = "128 passed",
    nextWidgets = "Widgets for the home screen",
    variantsTitle = "Onboarding, two versions",
    variantA = "Version A: one screen",
    variantB = "Version B: three short steps",
    everythingSoFar = "Everything done so far",
    latestReport = "Latest report",
    oneReport = "Report",
    createReport = "Create report",
    reportNote = "It will be saved in the project’s artifacts folder and ignored by Git.",
    limits = "Limits",
    limitSession = "Session",
    limitWeekly = "Weekly",
    limitUsed = "%d% used",
    limitResetsSession = "2h 5m",
    limitResetsCodex = "3h 40m",
    limitResetsWeekly = "3d 4h",
    paceAhead = "ahead of an even pace",
    paceRoom = "with room to spare",
    paceEven = "on an even pace",
    skillReview = "Reviews SwiftUI changes for layout and accessibility",
    skillNotes = "Writes release notes from the work merged since the last version",
    serverGitHub = "Issues and pull requests",
    serverXcode = "Builds and tests in Xcode",
    twoDaysAgo = "2 days ago",
    lastWeek = "last week",
    today = "today",
    cmdReview = "Review the changes on this branch",
    cmdTest = "Run the tests and explain what failed",
    cmdNotes = "[version] — Write the release notes",
    reportEyebrow = "One task · one report",
    reportChanged = "What changed",
    reportChecked = "How it was checked",
    reportBefore = "Before",
    reportAfter = "After",
    reportInside = "What is inside",
    reportDemoNote = "This report is part of the demo. Real reports are written by Bulava on your Mac, from the work it actually did.",
    syncReportSummary = "The last expense of the day now syncs right away. The sync remembers the token iCloud returns instead of a date, so nothing entered at the same second can fall between two syncs.",
    chartsReportSummary = "The charts use the asset catalogue's colours, so the grid, the bars and the labels stay readable in dark mode. The widgets use the same colours.",
    landingReportSummary = "The first screen says what the place is, when it is open and where, in 31 words instead of 94.",
    landingBeforeCopy = "Welcome to Harbor Coffee, a place where every cup tells a story. Since 2014 we have been roasting beans with passion and care, bringing the finest flavours from around the world to our cozy corner by the harbour…",
    landingAfterCopy = "Coffee roasted on site, by the harbour. Open every day 7:00–19:00. Pier Street 4, next to the ferry.",
    variantReportSummary = "Each version was built on its own branch, with before and after pictures, so you can pick one and merge it.",
    genericReportSummary = "The change is made, the tests pass, and Codex reviewed it. On your Mac this page would show the real diff, the checks it ran and pictures of the result.",
    productReportSummary = "Everything that reached an end in Pocket Ledger: what was merged, what waits for you, and what is next.",
    planTitle = "What to build next",
    planAsk = "Look at what is left and tell me what to take next.",
    planAnswer = "Three things are ready to start. Each is written up with what it gives and what it costs; the choices are in the questions.",
    planQuestionsTitle = "Pocket Ledger: what next",
    planLede = "Three pieces of work are ready to start. Each one says what it gives and what it costs. Nothing starts until you choose.",
    questionsForYou = "Questions for you",
    openQuestions = "Open the questions",
    waitsForDecisions = "“%s” waits for your decisions",
    optTake = "Take it",
    optLater = "Later",
    optNo = "No",
    planWidgets = "Home Screen widgets",
    planWidgetsDetail = "Today’s spending at a glance, in two sizes.",
    planWidgetsDoc = "A small widget with today’s total and a medium one with the last five expenses. About a day of work; the numbers come from the ledger already on the phone, so nothing new is stored.",
    planExport = "CSV export",
    planExportDetail = "A month of expenses as a file for the accountant.",
    planExportDoc = "One file per month, with dates, amounts, categories and notes. Half a day. The accountant has asked twice.",
    planFamily = "A ledger shared with family",
    planFamilyDetail = "Two people writing to one ledger. Needs the sync reworked first.",
    planFamilyDoc = "The biggest of the three: about a week, most of it in the sync, which now assumes a single writer. Worth doing once the widgets and the export are out.",
    planDemoNote = "These questions are part of the demo. On your Mac, Bulava shows the ones an agent really asks, beside the report it wrote.",
)

private val UK = EN.copy(
    language = "uk",
    macName = "Демо-Mac",
    you = "Ви",
    statusWorking = "Bulava працює",
    statusReplied = "Bulava відповіла",
    statusNeedsAnswer = "Потрібна ваша відповідь",
    statusNeedsOk = "Потрібна ваша згода",
    statusRunning = "Працює",
    statusReportReady = "Звіт готовий",
    statusMerged = "Влито",
    statusNext = "Далі",
    writing = "Пише відповідь",
    stop = "Зупинити",
    stopped = "Зупинено. Більше нічого не зроблено.",
    edit = "Редагувати",
    notDelivered = "Не доставлено",
    notInDemo = "Цього в демо немає. З Bulava на вашому Mac кнопка робить те, що на ній написано.",
    alreadyHandled = "Це вже зроблено.",
    untitled = "Новий чат",
    automatic = "Автоматично",
    automaticAt = "Автоматично · %s",
    newestOfEach = "Найновіші",
    fixedVersion = "Конкретна версія",
    claudeThinks = "Глибина Claude",
    codexThinks = "Глибина Codex",
    low = "Низька",
    medium = "Середня",
    high = "Висока",
    veryHigh = "Дуже висока",
    maximum = "Максимальна",
    readyEngine = "Рушій роботи встановлено",
    readyClaude = "Claude Code увійшов в акаунт",
    readyCodex = "Codex увійшов в акаунт",
    yesDoIt = "Так, зроби",
    notNow = "Не зараз",
    leftAsIs = "Лишили як є.",
    openReport = "Відкрити звіт",
    askForChanges = "Попросити змін",
    mergeIt = "Влити",
    mergeConfirm = "Зміна піде в main.",
    merged = "Влито в main. Вийде з наступною збіркою.",
    workingOnIt = "Працюю над цим",
    reviewedReady = "Codex перевірив · готово для вас",
    trustTitle = "Claude Code питає дозволу, коли вперше працює в теці.",
    trustAndSend = "Довіряю, надіслати",
    ledgerBrief = "Облік витрат для iPhone",
    ledgerSummary = "Застосунок на SwiftUI із синхронізацією через iCloud і віджетами.",
    ledgerRules = "Тільки нативне. Жодної сторонньої аналітики. Кожна зміна — з тестом.",
    cafeBrief = "Сайт кав’ярні",
    cafeSummary = "Статичний сайт: меню, години роботи, як знайти.",
    cafeRules = "Короткі речення. Сторінка меню має швидко відкриватися на телефоні.",
    syncTitle = "Чому синхронізація губить останню витрату?",
    syncAsk = "Чому синхронізація пропускає останню витрату за день?",
    syncSteps = listOf("Читає SyncEngine.swift", "Шукає lastSyncedAt"),
    syncAnswer = "Синхронізація просить в iCloud усе, що **після** `lastSyncedAt`, а `lastSyncedAt` дорівнює часу самої останньої витрати. Тож ця витрата ніколи не новіша за позначку і чекає, поки наступна не посуне її вперед.\n\n" +
        "```swift\nlet changes = try await store.changes(since: lastSyncedAt)   // строго після\nlastSyncedAt = changes.last?.date ?? lastSyncedAt\n```\n\n" +
        "Виправлення — запам’ятовувати токен, який повертає iCloud, а не дату, і додати тест на витрату, внесену за секунду до синхронізації.\n\nВиправити й додати тест?",
    syncWorkSteps = listOf("Змінює SyncEngine.swift", "Додає тест на останню витрату", "Запускає тести", "Codex перевіряє зміну"),
    syncTask = "Синхронізація не губить останню витрату",
    shipTitle = "Випустити 2.4 у TestFlight",
    shipAsk = "Випусти версію 2.4 у TestFlight",
    shipSteps = listOf("Перевіряє App Store Connect"),
    shipLead = "Усе готово до завантаження. Спершу потрібна одна відповідь.",
    shipEyebrow = "Потрібна ваша відповідь",
    shipHeadline = "Який номер збірки дати цьому завантаженню?",
    shipSituation = "У TestFlight уже є збірка 41 для версії 2.4. Повторне завантаження 41 відхилять.",
    shipItem = "Номер збірки",
    shipOption42Detail = "Наступний номер, більше нічого не змінюється",
    shipOptionBump = "Лишити 41 і підняти версію",
    shipOptionBumpDetail = "Застосунок стане 2.4.1 (41)",
    shipRecommendation = "42 — найменша зміна, яка пройде.",
    shipUnblocks = "Завантаження",
    shipAfterSteps = listOf("Архівує збірку", "Завантажує в App Store Connect"),
    shipDone = "Завантажено. TestFlight покаже її тестувальникам, щойно Apple закінчить обробку, зазвичай за пів години.",
    shipEvent = "Збірка в TestFlight.",
    chartsTitle = "Темна тема для графіків",
    chartsAsk = "Додай темну тему для графіків",
    chartsSteps = listOf("Читає ChartsView.swift", "Читає Assets.xcassets"),
    chartsAnswer = "Графіки малюються фіксованими кольорами, тож у темній темі сітка зникає, а підписи — чорні на майже чорному. " +
        "Семантичні кольори з каталогу ресурсів виправлять обидві речі, а віджети підхоплять їх самі.\n\nЗробити?",
    chartsWorkSteps = listOf("Переносить кольори графіків у каталог ресурсів", "Перевіряє контраст у світлій і темній темі", "Codex перевіряє зміну"),
    chartsTask = "Графіки в темній темі",
    landingTitle = "Скоротити текст на головній",
    landingAsk = "Текст на головній задовгий. Скороти.",
    landingSteps = listOf("Читає index.html", "Рахує слова в розділах"),
    landingAnswer = "Готово. Перший екран — 31 слово замість 94: що це за місце, коли відчинено і де. Решта переїхала під меню. Codex перевірив, що нічого, що шукає відвідувач, не загубилося.",
    landingTask = "Головна, коротше",
    genericSteps = listOf("Читає проєкт", "Шукає, де це живе"),
    genericWorkSteps = listOf("Вносить зміну", "Запускає тести", "Codex перевіряє зміну"),
    genericAnswer = { product, request ->
        "**Це демо**, тож відповідь написана заздалегідь. З Bulava на вашому Mac Claude Code зараз працював би в теці *$product* над «$request», і ви бачили б, як відповідь з’являється тут слово за словом.\n\n" +
            "Далі можна:\n1. Відповісти на питання, маючи код перед очима.\n2. Запропонувати зміну на ваше схвалення.\n3. Зробити її, дати Codex перевірити і принести звіт.\n\nПоказати третє?"
    },
    genericTask = { request -> "Зроблено: " + request.take(40) },
    kindFolder = "Тека",
    kindWebsite = "Сайт",
    canEdit = "Можна змінювати",
    askBeforeEditing = "Питати перед змінами",
    modified = "Змінено",
    added = "Додано",
    checkLastExpense = "Витрата, внесена за секунду до синхронізації, синхронізується",
    checkOldTests = "Наявні тести проходять",
    checkPassedCount = "128 пройдено",
    nextWidgets = "Віджети на головний екран",
    variantsTitle = "Онбординг, дві версії",
    variantA = "Версія A: один екран",
    variantB = "Версія B: три короткі кроки",
    everythingSoFar = "Усе, що вже зроблено",
    latestReport = "Останній звіт",
    oneReport = "Звіт",
    createReport = "Створити звіт",
    reportNote = "Він збережеться в папці artifacts проєкту й ігноруватиметься Git.",
    limits = "Ліміти",
    limitSession = "Сесія",
    limitWeekly = "Тиждень",
    limitUsed = "%d% ужито",
    limitResetsSession = "2 год 5 хв",
    limitResetsCodex = "3 год 40 хв",
    limitResetsWeekly = "3 дн 4 год",
    paceAhead = "швидше за рівний темп",
    paceRoom = "із запасом",
    paceEven = "у рівному темпі",
    skillReview = "Перевіряє зміни в SwiftUI: макет і доступність",
    skillNotes = "Пише нотатки до релізу з того, що влито від минулої версії",
    serverGitHub = "Задачі й pull request-и",
    serverXcode = "Збірка й тести в Xcode",
    twoDaysAgo = "2 дні тому",
    lastWeek = "минулого тижня",
    today = "сьогодні",
    cmdReview = "Переглянути зміни в цій гілці",
    cmdTest = "Запустити тести й пояснити, що впало",
    cmdNotes = "[версія] — Написати нотатки до релізу",
    reportEyebrow = "Одна задача · один звіт",
    reportChanged = "Що змінилося",
    reportChecked = "Як перевірено",
    reportBefore = "До",
    reportAfter = "Після",
    reportInside = "Що всередині",
    reportDemoNote = "Цей звіт — частина демо. Справжні звіти пише Bulava на вашому Mac, з роботи, яку вона справді зробила.",
    syncReportSummary = "Остання витрата за день тепер синхронізується одразу. Синхронізація пам’ятає токен iCloud, а не дату, тож нічого, внесене в ту саму секунду, не провалюється між двома синхронізаціями.",
    chartsReportSummary = "Графіки беруть кольори з каталогу ресурсів, тож сітка, стовпці й підписи читаються в темній темі. Віджети використовують ті самі кольори.",
    landingReportSummary = "Перший екран каже, що це за місце, коли відчинено і де, — 31 словом замість 94.",
    landingBeforeCopy = "Ласкаво просимо до Harbor Coffee, місця, де кожна чашка розповідає історію. З 2014 року ми з любов’ю обсмажуємо зерна, привозячи найкращі смаки з усього світу в наш затишний куточок біля гавані…",
    landingAfterCopy = "Кава власного обсмаження біля гавані. Щодня 7:00–19:00. Вул. Причальна, 4, біля порома.",
    variantReportSummary = "Кожну версію зроблено у власній гілці, з картинками до і після, — можна вибрати одну і влити.",
    genericReportSummary = "Зміну внесено, тести проходять, Codex її перевірив. На вашому Mac тут був би справжній diff, перевірки, які запускались, і картинки результату.",
    productReportSummary = "Усе, що дійшло до кінця в Pocket Ledger: що влито, що чекає на вас і що далі.",
    planTitle = "Що робимо далі",
    planAsk = "Подивись, що лишилось, і скажи, що брати далі.",
    planAnswer = "Готові до старту три речі. Про кожну написано, що вона дає і чого коштує, а вибір — у питаннях.",
    planQuestionsTitle = "Pocket Ledger: що далі",
    planLede = "Три шматки роботи готові до старту. Про кожен написано, що він дає і чого коштує. Ніщо не почнеться, доки ти не вибереш.",
    questionsForYou = "Питання до тебе",
    openQuestions = "Відкрити питання",
    waitsForDecisions = "«%s» чекає твоїх рішень",
    optTake = "Беремо",
    optLater = "Пізніше",
    optNo = "Ні",
    planWidgets = "Віджети на головному екрані",
    planWidgetsDetail = "Сьогоднішні витрати одним поглядом, два розміри.",
    planWidgetsDoc = "Малий віджет із сумою за сьогодні й середній з останніми п’ятьма витратами. Близько дня роботи; числа беруться з книги, яка вже є на телефоні, тож нічого нового не зберігається.",
    planExport = "Експорт у CSV",
    planExportDetail = "Витрати за місяць файлом для бухгалтера.",
    planExportDoc = "Один файл на місяць: дати, суми, категорії й нотатки. Пів дня. Бухгалтер просив уже двічі.",
    planFamily = "Спільна книга для родини",
    planFamilyDetail = "Двоє пишуть в одну книгу. Спершу треба переробити синхронізацію.",
    planFamilyDoc = "Найбільша з трьох: близько тижня, здебільшого в синхронізації, яка зараз розрахована на одного автора. Варто братися, коли вийдуть віджети й експорт.",
    planDemoNote = "Ці питання — частина демо. На вашому Mac Bulava показує ті, що справді ставить агент, поруч зі звітом, який він написав.",
)

private val RU = EN.copy(
    language = "ru",
    macName = "Демо-Mac",
    you = "Вы",
    statusWorking = "Bulava работает",
    statusReplied = "Bulava ответила",
    statusNeedsAnswer = "Нужен ваш ответ",
    statusNeedsOk = "Нужно ваше согласие",
    statusRunning = "Работает",
    statusReportReady = "Отчёт готов",
    statusMerged = "Влито",
    statusNext = "Дальше",
    writing = "Пишет ответ",
    stop = "Остановить",
    stopped = "Остановлено. Больше ничего не сделано.",
    edit = "Изменить",
    notDelivered = "Не доставлено",
    notInDemo = "Этого в демо нет. С Bulava на вашем Mac кнопка делает то, что на ней написано.",
    alreadyHandled = "Это уже сделано.",
    untitled = "Новый чат",
    automatic = "Автоматически",
    automaticAt = "Автоматически · %s",
    newestOfEach = "Новейшие",
    fixedVersion = "Конкретная версия",
    claudeThinks = "Глубина Claude",
    codexThinks = "Глубина Codex",
    low = "Низкая",
    medium = "Средняя",
    high = "Высокая",
    veryHigh = "Очень высокая",
    maximum = "Максимальная",
    readyEngine = "Движок работы установлен",
    readyClaude = "Claude Code вошёл в аккаунт",
    readyCodex = "Codex вошёл в аккаунт",
    yesDoIt = "Да, сделай",
    notNow = "Не сейчас",
    leftAsIs = "Оставили как есть.",
    openReport = "Открыть отчёт",
    askForChanges = "Попросить изменений",
    mergeIt = "Влить",
    mergeConfirm = "Изменение пойдёт в main.",
    merged = "Влито в main. Выйдет со следующей сборкой.",
    workingOnIt = "Работаю над этим",
    reviewedReady = "Codex проверил · готово для вас",
    trustTitle = "Claude Code спрашивает разрешения, когда впервые работает в папке.",
    trustAndSend = "Доверяю, отправить",
    ledgerBrief = "Учёт расходов для iPhone",
    ledgerSummary = "Приложение на SwiftUI с синхронизацией через iCloud и виджетами.",
    ledgerRules = "Только нативное. Никакой сторонней аналитики. Каждое изменение — с тестом.",
    cafeBrief = "Сайт кофейни",
    cafeSummary = "Статический сайт: меню, часы работы, как найти.",
    cafeRules = "Короткие предложения. Страница меню должна быстро открываться на телефоне.",
    syncTitle = "Почему синхронизация теряет последний расход?",
    syncAsk = "Почему синхронизация пропускает последний расход за день?",
    syncSteps = listOf("Читает SyncEngine.swift", "Ищет lastSyncedAt"),
    syncAnswer = "Синхронизация просит у iCloud всё, что **после** `lastSyncedAt`, а `lastSyncedAt` равен времени самого последнего расхода. Поэтому этот расход никогда не новее отметки и ждёт, пока следующий не сдвинет её вперёд.\n\n" +
        "```swift\nlet changes = try await store.changes(since: lastSyncedAt)   // строго после\nlastSyncedAt = changes.last?.date ?? lastSyncedAt\n```\n\n" +
        "Исправление — запоминать токен, который возвращает iCloud, а не дату, и добавить тест на расход, внесённый за секунду до синхронизации.\n\nИсправить и добавить тест?",
    syncWorkSteps = listOf("Меняет SyncEngine.swift", "Добавляет тест на последний расход", "Запускает тесты", "Codex проверяет изменение"),
    syncTask = "Синхронизация не теряет последний расход",
    shipTitle = "Выпустить 2.4 в TestFlight",
    shipAsk = "Выпусти версию 2.4 в TestFlight",
    shipSteps = listOf("Проверяет App Store Connect"),
    shipLead = "Всё готово к загрузке. Сначала нужен один ответ.",
    shipEyebrow = "Нужен ваш ответ",
    shipHeadline = "Какой номер сборки дать этой загрузке?",
    shipSituation = "В TestFlight уже есть сборка 41 для версии 2.4. Повторную загрузку 41 отклонят.",
    shipItem = "Номер сборки",
    shipOption42Detail = "Следующий номер, больше ничего не меняется",
    shipOptionBump = "Оставить 41 и поднять версию",
    shipOptionBumpDetail = "Приложение станет 2.4.1 (41)",
    shipRecommendation = "42 — самое маленькое изменение, которое пройдёт.",
    shipUnblocks = "Загрузка",
    shipAfterSteps = listOf("Архивирует сборку", "Загружает в App Store Connect"),
    shipDone = "Загружено. TestFlight покажет её тестировщикам, как только Apple закончит обработку, обычно за полчаса.",
    shipEvent = "Сборка в TestFlight.",
    chartsTitle = "Тёмная тема для графиков",
    chartsAsk = "Добавь тёмную тему для графиков",
    chartsSteps = listOf("Читает ChartsView.swift", "Читает Assets.xcassets"),
    chartsAnswer = "Графики рисуются фиксированными цветами, поэтому в тёмной теме сетка исчезает, а подписи — чёрные на почти чёрном. " +
        "Семантические цвета из каталога ресурсов исправят и то, и другое, а виджеты подхватят их сами.\n\nСделать?",
    chartsWorkSteps = listOf("Переносит цвета графиков в каталог ресурсов", "Проверяет контраст в светлой и тёмной теме", "Codex проверяет изменение"),
    chartsTask = "Графики в тёмной теме",
    landingTitle = "Сократить текст на главной",
    landingAsk = "Текст на главной слишком длинный. Сократи.",
    landingSteps = listOf("Читает index.html", "Считает слова в разделах"),
    landingAnswer = "Готово. Первый экран — 31 слово вместо 94: что это за место, когда открыто и где. Остальное переехало под меню. Codex проверил, что ничего, что ищет посетитель, не потерялось.",
    landingTask = "Главная, короче",
    genericSteps = listOf("Читает проект", "Ищет, где это живёт"),
    genericWorkSteps = listOf("Вносит изменение", "Запускает тесты", "Codex проверяет изменение"),
    genericAnswer = { product, request ->
        "**Это демо**, поэтому ответ написан заранее. С Bulava на вашем Mac Claude Code сейчас работал бы в папке *$product* над «$request», и вы видели бы, как ответ появляется здесь слово за словом.\n\n" +
            "Дальше можно:\n1. Ответить на вопрос, глядя в код.\n2. Предложить изменение на ваше одобрение.\n3. Сделать его, дать Codex проверить и принести отчёт.\n\nПоказать третье?"
    },
    genericTask = { request -> "Сделано: " + request.take(40) },
    kindFolder = "Папка",
    kindWebsite = "Сайт",
    canEdit = "Можно менять",
    askBeforeEditing = "Спрашивать перед изменениями",
    modified = "Изменён",
    added = "Добавлен",
    checkLastExpense = "Расход, внесённый за секунду до синхронизации, синхронизируется",
    checkOldTests = "Существующие тесты проходят",
    checkPassedCount = "128 пройдено",
    nextWidgets = "Виджеты на главный экран",
    variantsTitle = "Онбординг, две версии",
    variantA = "Версия A: один экран",
    variantB = "Версия B: три коротких шага",
    everythingSoFar = "Всё, что уже сделано",
    latestReport = "Последний отчёт",
    oneReport = "Отчёт",
    createReport = "Создать отчёт",
    reportNote = "Он сохранится в папке artifacts проекта и будет игнорироваться Git.",
    limits = "Лимиты",
    limitSession = "Сессия",
    limitWeekly = "Неделя",
    limitUsed = "%d% использовано",
    limitResetsSession = "2 ч 5 мин",
    limitResetsCodex = "3 ч 40 мин",
    limitResetsWeekly = "3 дн 4 ч",
    paceAhead = "быстрее ровного темпа",
    paceRoom = "с запасом",
    paceEven = "в ровном темпе",
    skillReview = "Проверяет изменения в SwiftUI: вёрстку и доступность",
    skillNotes = "Пишет заметки к релизу из того, что влито с прошлой версии",
    serverGitHub = "Задачи и pull request-ы",
    serverXcode = "Сборка и тесты в Xcode",
    twoDaysAgo = "2 дня назад",
    lastWeek = "на прошлой неделе",
    today = "сегодня",
    cmdReview = "Просмотреть изменения в этой ветке",
    cmdTest = "Запустить тесты и объяснить, что упало",
    cmdNotes = "[версия] — Написать заметки к релизу",
    reportEyebrow = "Одна задача · один отчёт",
    reportChanged = "Что изменилось",
    reportChecked = "Как проверено",
    reportBefore = "До",
    reportAfter = "После",
    reportInside = "Что внутри",
    reportDemoNote = "Этот отчёт — часть демо. Настоящие отчёты пишет Bulava на вашем Mac, по работе, которую она действительно сделала.",
    syncReportSummary = "Последний расход за день теперь синхронизируется сразу. Синхронизация помнит токен iCloud, а не дату, поэтому ничего, внесённое в ту же секунду, не проваливается между двумя синхронизациями.",
    chartsReportSummary = "Графики берут цвета из каталога ресурсов, поэтому сетка, столбцы и подписи читаются в тёмной теме. Виджеты используют те же цвета.",
    landingReportSummary = "Первый экран говорит, что это за место, когда открыто и где, — 31 словом вместо 94.",
    landingBeforeCopy = "Добро пожаловать в Harbor Coffee, место, где каждая чашка рассказывает историю. С 2014 года мы с любовью обжариваем зёрна, привозя лучшие вкусы со всего мира в наш уютный уголок у гавани…",
    landingAfterCopy = "Кофе своей обжарки у гавани. Каждый день 7:00–19:00. Ул. Причальная, 4, у парома.",
    variantReportSummary = "Каждая версия сделана в своей ветке, с картинками до и после, — можно выбрать одну и влить.",
    genericReportSummary = "Изменение внесено, тесты проходят, Codex его проверил. На вашем Mac здесь был бы настоящий diff, запущенные проверки и картинки результата.",
    productReportSummary = "Всё, что дошло до конца в Pocket Ledger: что влито, что ждёт вас и что дальше.",
    planTitle = "Что делаем дальше",
    planAsk = "Посмотри, что осталось, и скажи, что брать дальше.",
    planAnswer = "К старту готовы три вещи. Про каждую написано, что она даёт и чего стоит, а выбор — в вопросах.",
    planQuestionsTitle = "Pocket Ledger: что дальше",
    planLede = "Три куска работы готовы к старту. Про каждый написано, что он даёт и чего стоит. Ничего не начнётся, пока ты не выберешь.",
    questionsForYou = "Вопросы к тебе",
    openQuestions = "Открыть вопросы",
    waitsForDecisions = "«%s» ждёт твоих решений",
    optTake = "Берём",
    optLater = "Позже",
    optNo = "Нет",
    planWidgets = "Виджеты на главном экране",
    planWidgetsDetail = "Сегодняшние расходы одним взглядом, два размера.",
    planWidgetsDoc = "Маленький виджет с суммой за сегодня и средний с последними пятью расходами. Около дня работы; числа берутся из книги, которая уже есть на телефоне, так что ничего нового не хранится.",
    planExport = "Экспорт в CSV",
    planExportDetail = "Расходы за месяц файлом для бухгалтера.",
    planExportDoc = "Один файл на месяц: даты, суммы, категории и заметки. Полдня. Бухгалтер просил уже дважды.",
    planFamily = "Общая книга для семьи",
    planFamilyDetail = "Двое пишут в одну книгу. Сначала нужно переделать синхронизацию.",
    planFamilyDoc = "Самая большая из трёх: около недели, в основном в синхронизации, которая сейчас рассчитана на одного автора. Стоит браться, когда выйдут виджеты и экспорт.",
    planDemoNote = "Эти вопросы — часть демо. На вашем Mac Bulava показывает те, что действительно задаёт агент, рядом с отчётом, который он написал.",
)
